### ISSUE TITLE
consider not storing the user's steam password in plaintext

### ISSUE THREAD

**Issue by cheatfreak47** [RussDev7/TerrariaDepotDownloader#3]
As the title says, it's probably a bad idea to store the user's steam password in a paintext file.
I don't know what solution to offer, but just about anything would be an improvement over this.

**Comment by RussDev7** [comment]
Thank you for the concern and I completely agree. I will look into encrypting the stored password.

**Comment by RussDev7** [comment]
This is now resolved in commit 6809fc8fae4ae6d69e19d47048920664d0045782.

**Comment by cheatfreak47** [comment]
That is a significant improvement, obviously a sophisticated attacker could still work their way to the password, but this adds a barrier at least that is enough that it's a significantly lesser security risk. Good job.
